services:
  stats-server:
    build: stat/stat-server/
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/StatServDB
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6666:5432"
    environment:
      - POSTGRES_DB=StatServDB
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

#  ewm-service:
#    build: main-service/
#    container_name: main-server
#    ports:
#      - "8080:8080"
#    depends_on:
#      ewm-db:
#        condition: service_healthy
#      stats-server:
#        condition: service_started
#    environment:
#      - STATS_SERVER_URL=http://stats-server:9090
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/MainServDB
#      - POSTGRES_USER=dbuser
#      - POSTGRES_PASSWORD=12345
#
#  ewm-db:
#    image: postgres:16.1
#    container_name: main-db
#    ports:
#      - "3333:5432"
#    environment:
#      - POSTGRES_DB=MainServDB
#      - POSTGRES_USER=dbuser
#      - POSTGRES_PASSWORD=12345
#    healthcheck:
#      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
#      timeout: 5s
#      interval: 5s
#      retries: 10